### ISSUE TITLE
crash on api23 x86 simulator

### ISSUE THREAD

**Issue by imyslovsky** [idnow/de.idnow.android-sample#7]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.test.dev-1/lib/x86/libvpx.so: has text relocations
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                              at java.lang.System.loadLibrary(System.java:1076)
                                                                              at com.google.libvpx.LibVpxCom.<clinit>(LibVpxCom.java:17)

**Comment by arminbauer** [comment]
Hello,

The VP8 video codec needs native libraries which are provided in the jniLibs. Can you check if your compiled version has the native libraries for x86 included?

All the best,
Armin

**Comment by imyslovsky** [comment]
Hello, 
it has these libraries, problem that these libs has text relocations which is not allowed on api23

**Comment by tcmaps** [comment]
btw: this causes IDnow to crash on Zenfone 2 (x86+6.0)

**Comment by rafaelaguerra** [comment]
It's not just with api 23. I think it's related with x86 arch
